name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PlatformIO
      uses: platformio/setup-platformio@v3
      
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: |
          ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/platformio.ini') }}
        
    - name: Build library
      run: |
        pio run --environment library_test
        
    - name: Run tests
      run: |
        pio test --environment library_test
        
    - name: Check library structure
      run: |
        pio lib check 